services:
    react-app:
        container_name: react_sorcery_dev
        build:
            context: ..
            dockerfile: docker/ui/Dockerfile.dev
        ports:
            - ${PORT_HOST_MACHINE_DEV}:3000
        volumes:
            - ..:/app
            - node_modules:/app/node_modules
        restart: unless-stopped

volumes:
    node_modules:
